window.nyanz = {}

window.descToIcon = {
		'Moderateorheavysnowinareawiththunder':'$ 6'
		'Patchylightsnowinareawiththunder':'"6'
		'Moderateorheavyraininareawiththunder':'8 6'
		'Patchylightraininareawiththunder':'7 6'
		'Moderateorheavyshowersoficepellets':'8 #'
		'Lightshowersoficepellets':'7 #'
		'Moderateorheavysnowshowers':'$'
		'Lightsnowshowers':'"'
		'Torrentialrainshower':'888'
		'Moderateorheavyrainshower':'8'
		'Lightrainshower':'7'
		'Heavysnow':'$$'
		'Patchyheavysnow':'$"'
		'Moderatesnow':'#'
		'Patchymoderatesnow':'#"'
		'Lightsnow':'"'
		'Patchylightsnow':'"'
		'ModerateorHeavyfreezingrain':'8"'
		'Lightfreezingrain':'7"'
		'Heavyrain':'88'
		'Moderaterain':'77'
		'Overcast':'5 9'
		'Cloudy':'5%5'
		'Partlycloudy':'3'
		'Clear/Sunny':'1 2'
		'Sunny':'1'
		'Patchyrainnearby': '7'
	}