window.nyanz = {}

window.descToIcon = {
		'Moderateorheavysnowinareawiththunder':'X O'
		'Patchylightsnowinareawiththunder':'UO'
		'Moderateorheavyraininareawiththunder':'R O'
		'Patchylightraininareawiththunder':'Q O'
		'Moderateorheavyshowersoficepellets':'R W'
		'Lightshowersoficepellets':'Q W'
		'Moderateorheavysnowshowers':'X'
		'Lightsnowshowers':'U'
		'Torrentialrainshower':'RRR'
		'Moderateorheavyrainshower':'R'
		'Lightrainshower':'Q'
		'Heavysnow':'XX'
		'Patchyheavysnow':'XU'
		'Moderatesnow':'W'
		'Patchymoderatesnow':'WU'
		'Lightsnow':'U'
		'Patchylightsnow':'U'
		'ModerateorHeavyfreezingrain':'RU'
		'Lightfreezingrain':'QU'
		'Heavyrain':'RR'
		'Moderaterain':'QQ'
		'Overcast':'N S'
		'Cloudy':'N%N'
		'Partlycloudy':'H'
		'Clear/Sunny':'A B'
		'Sunny':'B'
		'Patchyrainnearby': 'Q'
	}